services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: ppm-laravel-app:latest
    container_name: ppm-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: ppm-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    container_name: ppm-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=laravel
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    container_name: ppm-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data:
